#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-AuthCookieDBI
version:      2.03
version_from: AuthCookieDBI.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    Apache2::Constants:             0
    Date::Calc:                    0
    Apache::DBI:                   0
    Apache2::AuthCookie:            3.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
