# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-AuthCookieDBI
version:      
version_from: 
installdirs:  site
requires:
    Apache2::AuthCookie:           3.08
    Apache2::Const:                0
    Apache::DBI:                   0.91
    Date::Calc:                    0
    Digest::MD5:                   0
    mod_perl2:                     1.999022

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
